force-app/main/default/objects/Game__c/Game__c.object-meta.xml
<CustomObject>
    <label>Game</label>
    <nameField>
        <displayFormat>G-{0000}</displayFormat>
        <label>Game Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Games</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Output__c/Output__c.object-meta.xml
<CustomObject>
    <label>Output</label>
    <nameField>
        <label>Output Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Output</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Output__c/fields/Game__c.field-meta.xml
<CustomField>
    <fullName>Game__c</fullName>
    <label>Game</label>
    <referenceTo>Game__c</referenceTo>
    <relationshipLabel>Output</relationshipLabel>
    <relationshipName>Output</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/InvocableDelete 2.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 12-17-2024
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public with sharing class InvocableDelete {
    

    public class getGame {
        @InvocableVariable(required=true)
        public ID recordId;
   }

   @InvocableMethod(label = 'Hard Delete')
        Public static void deleteRecords(List<getGame> getGames){
        //List<Output__c> outputs = [
          //      SELECT Id
            //    FROM Output__c
              //  WHERE Game__c = :getGames.recordId
            //];
// Collect all Game__c IDs for querying related Output__c records
        Set<Id> gameIds = new Set<Id>();
        for (GetGame input : getGames) {
            if (input.recordId != null) {
                gameIds.add(input.recordId);
            }
        }

 // Query related Output__c records
        List<Output__c> outputsToDelete = [
            SELECT Id
            FROM Output__c
            WHERE Game__c IN :gameIds
        ];


        try {
             delete outputsToDelete;
              Database.emptyRecycleBin(outputsToDelete);
                } catch (DmlException e) {
    // Process exception here
}
   }
}